# Generated by Django 2.2.4 on 2019-08-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_auto_20190809_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
